project:
  type: website
  output-dir: docs
  resources: CNAME
  preview:
    port: 4200

website:
  title: "DanteVision"
  favicon: "/images/dv_favicon.png"
  site-url: dantevision.com
  
  navbar:
    title: " "
    logo: "/images/dantevision_logo.png"
    background: white
    foreground: "#042426"
    pinned: true
    
    right:
      - text: "Home"
        href: "#"
      - text: "Product"
        href: "#product"
      - text: "Service"
        href: "#service"
      - text: "News"
        file: "#news"
      # - text: "Blog"
      #   file: blog.qmd

    
    collapse: true
    toggle-position: "right"

  search: false
    
format:
  html:
    theme:
    - cosmo
    - styles.scss
    css: 
      - css/bootstrap-grid.css
    
    section-divs: true
      
    page-layout: custom
    
    mainfont: 'NanumSquare, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji'

    include-in-header:
      - file: google_analytics.html
      - text: '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>'
      - text: '<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@2.0/nanumsquare.css">'
      - text: '<script src="https://kit.fontawesome.com/98e6e57c15.js" crossorigin="anonymous"></script>'

    include-after-body:
      - file: js_code.html
      - file: footer.html

