project:
  type: website
  output-dir: docs
  resources: CNAME
  preview:
    port: 4242

website:
  title: "DanteVision | 단테비전"
  favicon: "/images/dv_favicon.png"
  site-url: dantevision.com
  
  navbar:
    title: " "
    logo: "/images/dantevision_logo.png"
    background: white
    foreground: "#042426"
    pinned: true
    
    right:
      - text: "Home"
        href: "#"
      - text: "Product"
        href: "#product"
      - text: "Service"
        href: "#service"
      - text: "News"
        file: "#news"

    collapse: true
    toggle-position: "right"

  search: false
    
format:
  html:
    theme:
    - cosmo
    - styles.scss

    css: 
      - css/bootstrap-grid.css
    
    page-layout: custom
    mainfont: 'Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, Helvetica Neue, Segoe UI, Apple SD Gothic Neo, Noto Sans KR, Malgun Gothic, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, sans-serif'

    include-in-header:
      - file: google_analytics.html
      - text: '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>'
      - text: '<script src="https://kit.fontawesome.com/98e6e57c15.js" crossorigin="anonymous"></script>'
      - text: '<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" />'

    include-after-body:
      - file: js_code.html
      - file: footer.html

