project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: "DanteVision"
  favicon: "/images/dv_favicon.png"
  
  # page-footer:
  #   background: dark
  #   foreground: white
  #   
  #   left: 
  #     - "<a href=#><img src='img/dantevision_white_logo.png' class='img-fluid mb-1' alt='DanteVision' width='180'></a>"
  #     - "(주) 단테비전 | 대표자: 계형일 | 사업자 번호: 000-00-00000"
  #     - "주소: 경기도 안양시 동안구"
  #     - "이메일: cs@dantevision.com"
  #     
  #   center:
  #     - text: "About"
  #       href: about.qmd
  #       
  #   right:
  #     - icon: linkedin
  #       href: https://twitter.com/quarto_pub
  #       aria-label: DanteVision LinkedIn


  navbar:
    title: " "
    logo: "/images/dantevision_logo.png"
    background: white
    foreground: "#042426"
    pinned: true
    
    right:
      - text: "Home"
        href: "#"
      - text: "Product"
        href: "#product"
      - text: "Service"
        href: "#service"
      - text: "News"
        file: "#news"
      # - text: "Blog"
      #   file: blog.qmd

    
    collapse: true
    toggle-position: "left"

  search: false
    
format:
  html:
    theme: [default, css/styles.scss]
    css: [css/bootstrap-grid.css]
    page-layout: custom
    
    mainfont: 'NanumSquare, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji'

    include-in-header:
      - text: '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>'
      - text: '<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@2.0/nanumsquare.css">'
      - text: '<script src="https://kit.fontawesome.com/98e6e57c15.js" crossorigin="anonymous"></script>'
      
    include-after-body:
      - file: footer.html

